BooksShop.WebApp/Areas/Admin/Controllers/CategoryController.cs
using BooksShop.DataAccess.Repository;
using BooksShop.DataAccess.Repository.IReponsitory;
using BooksShop.Models.Models;
using BooksShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BooksShop.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Category> categories = _unitOfWork.Category.GetAll().ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public  IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "create successfully ";
            }
            return RedirectToAction("Index");
        }


      
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                throw new ArgumentNullException("id");
            }
            Category? category = _unitOfWork.Category.Get(temp => temp.Id == id);
            if(category == null)
            {
               return NotFound();
            }

            return View(category);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Category? category)
        {
            if (category == null)
            {
                throw new ArgumentNullException();
            }

            if(ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["edit"] = "edit successfully ";

                return RedirectToAction("Index");   
            }

            return View();
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id ==0)
            {
                throw new ArgumentNullException();
            }

            Category? obj = _unitOfWork.Category.Get(temp => temp.Id == id);

            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();

            TempData["deleted"] = "deleted successfully ";


            return RedirectToAction("Index");
        }

    }
}

BooksShop.WebApp/Areas/Admin/Controllers/CompanyController.cs
using BooksShop.DataAccess.Data;
using BooksShop.DataAccess.Repository.IReponsitory;
using BooksShop.Models.Models;
using BooksShop.Models.Models.ViewsModels;
using BooksShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net;

namespace BooksShop.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Company> Companys = _unitOfWork.Company.GetAll().ToList();

            return View(Companys);
        }

        public IActionResult UpSert(int? id)// combine update and insert
        {   
            Company obj = new Company();
            if (id == null) return View(obj);
            //update
             obj = _unitOfWork.Company.Get(temp => temp.Id == id);
            if (obj == null) return NotFound();
            return View(obj);




        }

        [HttpPost]
        public IActionResult UpSert(Company obj)//Upsert
        {
            if (ModelState.IsValid)
            {

                if (obj.Id == 0)
                {
                    _unitOfWork.Company.Add(obj);
                }
                else
                {
                    _unitOfWork.Company.Update(obj);

                }

                _unitOfWork.Save();
                TempData["success"] = "Created successfull";

                return RedirectToAction("Index");
            }
            else
            {
                // Extract error messages
                var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                                     .Select(e => e.ErrorMessage)
                                                     .ToList();

                // Return error response to client
                return BadRequest(errorMessages); // You can return error messages to client in a suitable format
            }



        }


        public IActionResult Delete(int id)
        {
            if (id == 0) throw new ArgumentNullException("id cant be null");
            Company Company = _unitOfWork.Company.Get(temp => temp.Id == id);
            if (Company == null) return NotFound();

            _unitOfWork.Company.Remove(Company);
            _unitOfWork.Save();
            TempData["deleted"] = "Deleted successfull";

            return RedirectToAction("Index");
        }
    }
}

BooksShop.WebApp/Areas/Admin/Controllers/OrderController.cs
using BooksShop.DataAccess.Repository.IReponsitory;
using BooksShop.Models.Models;
using BooksShop.Models.Models.ViewsModels;
using BooksShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Security.Claims;

namespace BooksShop.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        
        public IActionResult Index()
        {
            IEnumerable<OrderHeader> objorderHeader;
           
            if(User.IsInRole(SD.Role_Admin)||User.IsInRole(SD.Role_Employee))
            {
                objorderHeader = _unitOfWork.OrderHeader.GetAll(includeProperties:"ApplicationUser") ;
            }
            else
            {
                var claimIndentity = (ClaimsIdentity)User.Identity;
                var userId = claimIndentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                objorderHeader = _unitOfWork.OrderHeader.GetAll(u => u.ApplicationUserId == userId,includeProperties: "ApplicationUser");
            }

            return View(objorderHeader);
        }

        public IActionResult Detail(int orderId)
        {
            OrderVM = new()
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
                OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product"),
            };
            return View(OrderVM);
        }

        [HttpPost]
        [Authorize(Roles =SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
            orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeaderFromDb.Address = OrderVM.OrderHeader.Address;
            orderHeaderFromDb.City = OrderVM.OrderHeader.City;
            orderHeaderFromDb.State = OrderVM.OrderHeader.State;
            orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;

            _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _unitOfWork.Save();
            return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult StartProcessing()
        {
            _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["success"] = "OrderDetails is in Process";
            return RedirectToAction("Detail",new {orderId = OrderVM.OrderHeader.Id});
        }

        [HttpPost]
        [Authorize(Roles =SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult ShipOrder()
        {

            var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u=>u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.OrderStatus = SD.StatusShipped;
            orderHeaderFromDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            orderHeaderFromDb.ShipingDate = DateTime.Now;
            orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
            if (orderHeaderFromDb.PaymentStatus == SD.PaymentSatusDelaydPayment)
            {
                orderHeaderFromDb.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }

            _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _unitOfWork.Save();
            TempData["success"] = "OrderDetails is Shipped";
            return RedirectToAction("Detail", new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult CancelOrder()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            if(orderHeader.PaymentStatus  == SD.PaymentSatusApproved)
            {
                var options = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentId,
                };

                var service = new RefundService();
                Refund refund = service.Create(options);
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusRefunded);
            }
            else
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
            _unitOfWork.Save();
            TempData["success"] = "cancelled successfully";
            return RedirectToAction("Detail", new {orderId =  orderHeader.Id});
        }


        [ActionName("Detail")]
        [HttpPost]
        public IActionResult Details_PAY_Now()
        {
            OrderVM.OrderHeader = _unitOfWork.OrderHeader.Get(u =>u.Id == OrderVM.OrderHeader.Id, "ApplicationUser");
            OrderVM.OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderHeader.Id == OrderVM.OrderHeader.Id, "Product");

            var domain = Request.Scheme + "://" + Request.Host.Value + "/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"admin/order/PaymentConfirm?id={OrderVM.OrderHeader.Id}",
                CancelUrl = domain + $"admin/order/detail?orderId={OrderVM.OrderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };

            foreach (var item in OrderVM.OrderDetails)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Price * 100), // $20.50 => 2050
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Title
                        }
                    },
                    Quantity = item.Count
                };
                options.LineItems.Add(sessionLineItem);
            }
            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.OrderHeader.UpdateStripePaymentID(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);

            return new StatusCodeResult(303);
        }

        
        public IActionResult PaymentConfirm(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(temp => temp.Id == id, includeProperties: "ApplicationUser");
            if (orderHeader.PaymentStatus == SD.PaymentSatusDelaydPayment)
            { //this is an order by company 
                var service = new SessionService();
                Session session = service.Get(orderHeader.SesstionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.OrderHeader.UpdateStripePaymentID(id, session.Id, session.PaymentIntentId);
                    _unitOfWork.OrderHeader.UpdateStatus(id, orderHeader.OrderStatus, SD.PaymentSatusApproved);
                    _unitOfWork.Save();
                }
            }
            return View(orderHeader.Id);
        }

    }
}

BooksShop.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
     <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class=" bg-dark navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index"> BookShop</a>

                <div class ="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1  ms-3">
                        <li class="nav-item">
                            <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="nav-link text-light" >HOME</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Order" asp-action="Index" class="nav-link text-light">Manage Order</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {

                            <li class="nav-item dropdown  ms-3">
                                <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managent
                                </button>
                                <ul class="dropdown-menu dropdown-menu-dark ">
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-light ps-2" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-light ps-2" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-light ps-2" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li> <hr class="dropdown-divider " style="border-color:white;" /></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Cart" asp-action="Index" >
                                <i class="bi bi-cart" ></i> &nbsp; (0)
                            </a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
  

    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />

            @RenderBody()
        </main>
    </div>

    <script type="text/javascript" src="/lib/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/lib/bootstrap/js/bootstrap.min.js" ></script>
    <script  src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BooksShop.WebApp/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');    
    </script>
}
@if(TempData["edit"] != null)
{
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["edit"]');
    </script>
}


@if(TempData["deleted"] != null)
{
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["deleted"]');
    </script>
}

BooksShop.WebApp/Views/Shared/_ValidatorPartial.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"></script>